name: Run tests on Debian

on: [push, pull_request]

jobs:
  debian-bookworm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v3

      - name: ansible check with debian bookworm (12)
        uses: roles-ansible/check-ansible-debian-bookworm-action@v1
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"

  debian-bullseye:
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v3

      - name: ansible check with debian bullseye (11)
        uses: roles-ansible/check-ansible-debian-bullseye-action@main
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"

  debian-buster:
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v3

      - name: ansible check with debian buster (10)
        uses: roles-ansible/check-ansible-debian-buster-action@master
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"
